# fly.toml app configuration file generated for cyber-sim-sdk on 2026-05-02T14:25:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cyber-sim-sdk'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  ports = []

  [services.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

  [[services.http_checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'get'
    path = '/api/status'
    protocol = 'http'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
